### ISSUE TITLE
Build failing, tests pass locally

### ISSUE THREAD

**Issue by jlord** [jlord/gardening#6]
Not sure why...

**Comment by hamishdickson** [comment]
I've had that problem a couple of times - do they fail if you run them again?

My errors were a mix of how travis-ci sleeps between tests and how callbacks work in node

**Comment by jlord** [comment]
Running them locally always worked, I just fiddled with the test some more got it to go green though, woo!

**Comment by hamishdickson** [comment]
Oh I meant running them again through travis-ci haha - glad you got it green though!
